#!/usr/bin/env bash

# ==============================================================================
# Terminal helpers
# ==============================================================================

# Tree
alias t='tree -C'
alias ta="tree -Ca"

# Utility
alias reload='source ~/.bashrc'
alias ea='mate -w ~/.dotfiles/bash/aliases && reload'
alias ee="mate ~/.dotfiles/bash/env"

# commands starting with % for pasting from web
alias %=' '

function cr() {
 cd ~/dev/repos/$*
}

# ls
alias ls='ls -G' # ls with color
alias a='ls -A' # -A all except literal . ..
alias la="ls -Alht"
alias l.='ls -d .[^.]*'
alias l='ls -lht'  # -l long listing, most recent first
alias lh="ls -lh"
alias ll='ls -lh'  # -l long listing, human readable, no group info
alias lt='ls -lt' # sort with recently modified first

alias c='clear'
alias cls='clear; ls'

alias s='cd ..'   # up one dir
alias cdd='cd -'  # goto last dir cd'ed from
alias cl='clear; l'
function cdc() {
    cd $1; ls
}

alias h='history'

alias md='mkdir -p'

function take() {
  mkdir -p "$1"
  cd "$1"
}

alias e='exit'

# Processes
alias tu='top -o cpu' # cpu
alias tm='top -o vsize' # memory

# ==============================================================================
# Git
# ==============================================================================

# Commit pending changes and quote all args as message
function gg() {
    git commit -v -a -m "$*"
}

# This works only if in the root of the Repository.
alias ungit="find . -name '.git' -maxdepth 1 | xargs rm -rf"

alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gco='git checkout'
alias gd='git diff'
alias gdm='git diff master'
alias gl='git pull'
alias gnp="git-notpushed"
alias gp='git push'
alias gst='git status'
alias gt='git status'
alias g='git status'
alias eg='mate .git/config'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"

# TextMate
alias et="mate"
alias ett="mate ."

# Rails
alias mr='mongrel_rails start'
alias ms='mongrel_rails stop'
alias rp='touch tmp/restart.txt'
alias sc='./script/console'
alias sg='./script/generate'
alias sp='./script/plugin'
alias ss='./script/server'
alias tlog='tail -f log/development.log'
alias ts='thin start'
alias rst='touch tmp/restart.txt'
alias scaffold='script/generate nifty_scaffold'
alias migrate='rake db:migrate db:test:clone'

# TDD / BDD
alias aa='autotest'
alias aaf='autotest -f' # Don't run all at start
alias aas="./script/autospec"

# From http://github.com/suztomo/dotfiles
function rmf(){
  for file in $*
  do
    __rm_single_file $file
  done
}

function __rm_single_file(){
  if ! [ -d ~/.Trash/ ]
  then
    command /bin/mkdir ~/.Trash
  fi

  if ! [ $# -eq 1 ]
  then
    echo "__rm_single_file: 1 argument required but $# passed."
    exit
  fi

  if [ -e $1 ]
  then
    BASENAME=`basename $1`
    NAME=$BASENAME
    COUNT=0
    while [ -e ~/.Trash/$NAME ]
    do
      COUNT=$(($COUNT+1))
      NAME="$BASENAME.$COUNT"
    done

    command /bin/mv $1 ~/.Trash/$NAME
  else
    echo "No such file or directory: $file"
  fi
}

# ==============================================================================
# Postgresql
# ==============================================================================

alias start-pg='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias stop-pg='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
