#!/usr/bin/env bash
# ==============================================================================
# Author => "Micah Woods"
# Date => "October 19 2010"
# ==============================================================================

# homebrew completion
if [ -f `brew --prefix`/Library/Contributions/brew_bash_completion.sh ]; then
  source `brew --prefix`/Library/Contributions/brew_bash_completion.sh
fi

# bash completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  source `brew --prefix`/etc/bash_completion
fi

# the following where taken from Ryan Bates dotfiles
complete -C ~/.bash/completion_scripts/rake_completion -o default rake
complete -C ~/.bash/completion_scripts/capistrano_completion -o default cap
